<a href="https://colab.research.google.com/github/Diogo-Spencer/Mec-nica-dos-S-lidos-1/blob/main/trabalho_pr%C3%A1tico_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a)

In [3]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.6f}'.format})

def versor(v1,v2,v3): return np.array([v1,v2,v3])

n1 = versor(0.373239,0.653484,0.658522)
n2 = versor(-0.653484,-0.318654,0.686599)
n3 = versor(0.658522,-0.686599,0.308108)

print('n1 = ',n1)
print('n2 = ',n2)
print('n3 = ',n3)

n1 =  [ 0.373239  0.653484  0.658522]
n2 =  [-0.653484 -0.318654  0.686599]
n3 =  [ 0.658522 -0.686599  0.308108]


Ortonormalidade

In [4]:
print('i = j: ')
print(f'np.dot(n1,n1) = {np.dot(n1,n1):.1f}')
print(f'np.dot(n2,n2) = {np.dot(n2,n2):.1f}')
print(f'np.dot(n3,n3) = {np.dot(n3,n3):.1f}')

i = j: 
np.dot(n1,n1) = 1.0
np.dot(n2,n2) = 1.0
np.dot(n3,n3) = 1.0


Ortogonalidade

In [5]:
print('i ne j: ')
print(f'np.dot(n2,n3) = {np.dot(n2,n3):.1f}')
print(f'np.dot(n1,n3) = {np.dot(n1,n3):.1f}')
print(f'np.dot(n1,n2) = {np.dot(n1,n2):.1f}')

i ne j: 
np.dot(n2,n3) = 0.0
np.dot(n1,n3) = 0.0
np.dot(n1,n2) = -0.0


como os vetores são ortogonais e ortonormados dá certo

Aij

In [6]:
np.set_printoptions(formatter={'float': '{: 0.6f}'.format})

def trans01(i0i1,i0j1,i0k1,j0i1,j0j1,j0k1,k0i1,k0j1,k0k1):
    linha0 = [i0i1,j0i1,k0i1]
    linha1 = [i0j1,j0j1,k0j1]
    linha2 = [i0k1,j0k1,k0k1]
    return np.array([linha0,linha1,linha2])

Aij = trans01(n1[0],n2[0],n3[0],n1[1],n2[1],n3[1],n1[2],n2[2],n3[2])
print(f'\n Matriz de mudanca de base de S0 para S1: \n Aij = \n {Aij}')


 Matriz de mudanca de base de S0 para S1: 
 Aij = 
 [[ 0.373239  0.653484  0.658522]
 [-0.653484 -0.318654  0.686599]
 [ 0.658522 -0.686599  0.308108]]


verificação do Aij

In [7]:
print('[Aij^T][Aij] = [I] = \n',np.dot(np.transpose(Aij),Aij))
print('\n det([Aij]) = ','{: 0.1f}'.format(np.linalg.det(Aij)))

[Aij^T][Aij] = [I] = 
 [[ 1.000000  0.000000  0.000001]
 [ 0.000000  1.000000 -0.000001]
 [ 0.000001 -0.000001  1.000000]]

 det([Aij]) =   1.0


sigma'

In [8]:
np.set_printoptions(formatter={'float': '{: 0.5f}'.format})

S0tn1 = np.array([[16.413],[1.575],[0]])
S0tn2 = np.array([[-27.193],[-1.650],[0]])
S0tn3 = np.array([[25.518],[0.310],[0]])
print('Componentes dos vetores tensao no referencial S0 :')
print('t(n1).S0 | t(n2).S0 | t(n3).S0')
for i in range(0,3):
    print(S0tn1[i],' ',S0tn2[i],' ',S0tn2[i])

Componentes dos vetores tensao no referencial S0 :
t(n1).S0 | t(n2).S0 | t(n3).S0
[ 16.41300]   [-27.19300]   [-27.19300]
[ 1.57500]   [-1.65000]   [-1.65000]
[ 0.00000]   [ 0.00000]   [ 0.00000]


In [9]:
np.set_printoptions(formatter={'float': '{: 0.5f}'.format})
S1tn1 = np.dot(Aij,S0tn1)
S1tn2 = np.dot(Aij,S0tn2)
S1tn3 = np.dot(Aij,S0tn3)

print('Componentes dos vetores tensao no referencial S1 :')
print('tn1.S1 | tn2.S1 | tn3.S1')
for i in range(0,3):
    print(S1tn1[i],' ',S1tn2[i],' ',S1tn2[i])

Componentes dos vetores tensao no referencial S1 :
tn1.S1 | tn2.S1 | tn3.S1
[ 7.15521]   [-11.22774]   [-11.22774]
[-11.22751]   [ 18.29597]   [ 18.29597]
[ 9.72693]   [-16.77430]   [-16.77430]


In [10]:
sigma1 = np.hstack((S1tn1,S1tn2,S1tn3))
print('sigma1 = \n', sigma1)

sigma1 = 
 [[ 7.15521 -11.22774  9.72689]
 [-11.22751  18.29597 -16.77439]
 [ 9.72693 -16.77430  16.59132]]


B)

In [11]:
Aji = np.transpose(Aij)
sigma0 = np.dot(Aji, np.dot(sigma1, np.transpose(Aji)))
print('\nsigma0 = \n', sigma0)



sigma0 = 
 [[ 40.70032  1.87016 -0.00007]
 [ 1.87026  1.34217 -0.00020]
 [ 0.00002  0.00000  0.00000]]


c)

d)Invariantes

In [12]:
I1 = np.trace(sigma0)
print('1º Invariante, I1 :', '{:.6f}'.format(I1))

I2 = 0.5*(np.trace(sigma0)**2 -np.trace(np.dot(sigma0,sigma0)))
print('2º Invariante, I2 :', '{:.6f}'.format(I2))

I3 = np.linalg.det(sigma0)
print('2º Invariante, I3 :', '{:.6f}'.format(I3))


1º Invariante, I1 : 42.042495
2º Invariante, I2 : 51.129129
2º Invariante, I3 : -0.000000


Como temos a regra de que I1>I2>I3:

In [13]:
sigmaI =np.array([[I2,0,0],[0,I1,0],[0,0,I3]])
print('sigmaI = \n', sigmaI)

sigmaI = 
 [[ 51.12913  0.00000  0.00000]
 [ 0.00000  42.04250  0.00000]
 [ 0.00000  0.00000 -0.00000]]


e)

In [14]:
import numpy as np
sigma0 = np.dot(Aji, np.dot(sigma1, np.transpose(Aji)))
print('\nsigma0 = \n', sigma0)



sigma0 = 
 [[ 40.70032  1.87016 -0.00007]
 [ 1.87026  1.34217 -0.00020]
 [ 0.00002  0.00000  0.00000]]


In [16]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.6f}'.format})

def versor(v1,v2,v3): return np.array([v1,v2,v3])

v = versor(1/np.sqrt(2),0.653484,1/np.sqrt(2))

print('v = ', v)


v =  [ 0.707107  0.653484  0.707107]


In [20]:
t=np.dot(v,sigma0)

print('t=', t)

t= [ 30.001675  2.199489 -0.000178]


In [30]:
sigma_nor= np.dot(v,np.transpose(t))

print('sigma_nor (MPa) =',sigma_nor)

sigma_nor (MPa) = 22.65159244889814


In [29]:
sigma_tan=np.sqrt(np.dot(t,t)+(sigma_nor)**2)

print('sigma_tan (Mpa) =', sigma_tan)

sigma_tan (Mpa) = 37.65677727760237
